* Целевая аудитория, география и проблематика
:PROPERTIES:
:ID:       6E42CA7C-D8B3-4BCB-8853-EF21A61035F7
:CUSTOM_ID: ta-geo-issue
:END:
- Описать свою целевую аудиторию, которую вы выбираете для работы
- Описать географию проекта
- Описать проблематику (не менее половины листа формата A4)

** Решение
:PROPERTIES:
:ID:       86462638-00EE-4D41-B374-EC524629A93C
:CUSTOM_ID: ta-geo-issue-r
:END:
*** Целевая аудитория
:PROPERTIES:
:ID:       4045E350-5BAA-42E1-BD99-C28457809CC4
:CUSTOM_ID: ta
:END:
Граждане России, возрастом 16-35 лет, изучающие английский язык для
общения, обучения и/или труда за рубежом, профессиональной
деятельности на территории России.

Отдельной группой самозахватываются дети, 8-18 лет, изучающие язык вне школьной программы
*** География проекта
:PROPERTIES:
:ID:       B7DE3568-6862-4192-8F15-3179B497C132
:CUSTOM_ID: geo
:END:
Вся Россия, ввиду интернет-направленности
*** Проблематика
:PROPERTIES:
:ID:       E853DBF1-33EC-4999-8E1E-E9FF4301408A
:CUSTOM_ID: issue
:END:
Английский язык – самый популярный язык международного общения в
мире. Это язык науки и технологий, предоставляющий гигантский пласт
знаний, доступ к которому необходим любому высококвалифицированному
специалисту для принятия решений соответствующих современности.

**** Влияние на умы посредством бесплатных сервисов
:PROPERTIES:
:ID:       FEBA3E35-DC49-4819-A5D1-8F6CC0EE2ECB
:CUSTOM_ID: minds
:END:
Сейчас стали довольно популярны различные бесплатные сервисы, которые
дают возможность используя свой смартфон получить неплохие навыки
выражения мыслей и чтения на английском языке. При этом они находятся
вне правового поля России, так как не имеют официальных
представительств на территории России. И имеют возможность мягкого
влияния на умы через множественное повторения заданий и содержащейся в
них информации. Как сказал один из главных основоположников
пропаганды: «Ложь, повторенная тысячу раз, становиться правдой»

Как пример: самое популярное приложение «Duolingo», где посредством
выполнения заданий c присутствием явных представителей LGBT, идет
тонкая пропаганда среди детей к вступлению в «Лигу сексуальных
извращений». Продвижение LGBT повестки прямо заявлено в блоге этой
компании:(https://blog.duolingo.com/lgbtq-representation-in-duolingo-stories-and-characters/).
Среди русскоязычных пользователей есть редкие, но все же возмущенные
подобным:
- https://zen.yandex.ru/media/krokoziabra/chto-menia-udivilo-v-prilojenii-duolingo--nalichie-nekotoryh-netradicionnyh-i-osujdaemyh-mnogimi-momentov-60d0d91a598aa70bd4b9cdf9
- https://zen.yandex.ru/media/young_tutor/3-prichiny-po-kotorym-vam-mojet-ne-ponravitsia-platforma-dlia-izucheniia-iazykov-duolingo-60e77b2f12d3b87671de0a91

Так же в этом приложении имеются примеры демонстрирующие неумеренное потребление алкоголя и табака.

**** Слабые исторические знания населения
:PROPERTIES:
:ID:       864C5541-65C8-41F9-9172-CE827B0E1C16
:CUSTOM_ID: knowledge
:END:
Множество русскоязычных знают только негативные факты о России, её
истории как прошлых периодов, так и новейшей. В подавляющем
большинстве случаев это сведения получаемые от «оппозиции»,
иностранных агентов и других элементов пытающихся дестабилизировать
обстановку и демотивировать людей от созидательной деятельности.

Также имеются те, кто относиться равнодушно к истории и сбрасывает её
за борт своего кругозора не видя практической применимости данной
информации. Недооценивая её влияние на настоящее и будущее. Начиная от
элементарного соотношения исторических деятелей и их влияния, до
изучения причинно-следственных связей повлекших за собой принятие
данного решении.

Из вышеназванных представителей имеются недюжинные умы, которые идут
на борьбу с системой, растрачивая свой созидательный потенциал. Либо
предпринимают действия чтобы «свалить из Рашки», тем самым создавая в
стране кадровый голод. И множество из них изучали или изучают
английский язык. Это особенно ярко проявилось в оттоке IT-специалистов
после начала спецоперации.
